import os
from PIL import Image

# --- CONFIGURATION ---
SOURCE_DIR = r'D:\Path\To\Your\Source'  # Thư mục gốc chứa ảnh
DEST_FILE = r'D:\Path\To\Your\Dest\Resources.mqh' # Nơi xuất file .mqh

def get_unique_name(root_dir, file_path):
    """Tạo tên biến duy nhất dựa trên đường dẫn tương đối"""
    rel_path = os.path.relpath(file_path, root_dir)
    # Thay thế các ký tự đặc biệt để thành tên biến hợp lệ trong C++
    unique_name = rel_path.replace(os.sep, "_").replace(".", "_").replace(" ", "_")
    return unique_name

def color_to_uint(r, g, b, a=255):
    """Convert RGBA sang định dạng uint ARGB của MQL5"""
    return (a << 24) | (r << 16) | (g << 8) | b

def generate_resources():
    all_files = []
    
    # 1. Quét toàn bộ thư mục để lấy danh sách file hợp lệ
    for root, _, files in os.walk(SOURCE_DIR):
        for filename in files:
            if filename.lower().endswith(('.bmp', '.png', '.jpg', '.jpeg')):
                full_path = os.path.join(root, filename)
                unique_name = get_unique_name(SOURCE_DIR, full_path)
                all_files.append({
                    'full_path': full_path,
                    'var_name': unique_name,
                    'enum_name': f"RESOURCE_{unique_name.upper()}"
                })

    if not all_files:
        print("Không tìm thấy file ảnh nào!")
        return

    # 2. Bắt đầu ghi file .mqh
    with open(DEST_FILE, 'w', encoding='utf-8') as f:
        f.write("//+------------------------------------------------------------------+\n")
        f.write("//|                                              Resources.mqh       |\n")
        f.write("//|                        Generated by Python Pixel Tool            |\n")
        f.write("//+------------------------------------------------------------------+\n\n")

        # --- PHẦN 1: DEFINE & ENUM ---
        f.write(f"#define TOTAL_RESOURCES {len(all_files)}\n\n")
        f.write("enum ENUM_RESOURCES {\n")
        for i, entry in enumerate(all_files):
            comma = "," if i < len(all_files) - 1 else ""
            f.write(f"   {entry['enum_name']}{comma}\n")
        f.write("};\n\n")

        # --- PHẦN 2: IMPLEMENTATION (MẢNG PIXEL) ---
        print(f"Đang convert {len(all_files)} files...")
        
        for entry in all_files:
            try:
                with Image.open(entry['full_path']) as img:
                    img = img.convert('RGBA')
                    width, height = img.size
                    entry['width'] = width
                    entry['height'] = height
                    
                    pixels = list(img.getdata())
                    
                    f.write(f"// Source: {entry['full_path']}\n")
                    f.write(f"const uint {entry['var_name']}[] = {{\n")
                    
                    pixel_data = [str(color_to_uint(p[0], p[1], p[2], p[3])) for p in pixels]
                    
                    # Ghi mảng theo cụm 10 số mỗi dòng cho gọn
                    for i in range(0, len(pixel_data), 10):
                        line = "   " + ",".join(pixel_data[i:i+10])
                        f.write(line + (",\n" if i + 10 < len(pixel_data) else "\n"))
                    
                    f.write("};\n\n")
            except Exception as e:
                print(f"Lỗi tại file {entry['full_path']}: {e}")

        # --- PHẦN 3: INITIALIZATION FUNCTION ---
        f.write("//+------------------------------------------------------------------+\n")
        f.write("//| Initialize Resources                                             |\n")
        f.write("//+------------------------------------------------------------------+\n")
        f.write("void InitResources(CResources &obj)\n")
        f.write("{\n")
        f.write(f"   // Cậu nhớ ép kiểu hoặc Resize mảng images của cậu tương ứng nhé\n")
        
        for entry in all_files:
            if 'width' in entry: # Chỉ ghi nếu convert thành công
                f.write(f"   obj.SetData({entry['enum_name']}, \"{entry['var_name']}\", {entry['width']}, {entry['height']}, {entry['var_name']});\n")
        
        f.write("}\n")

    print(f"Xong! File đã được lưu tại: {DEST_FILE}")

if __name__ == "__main__":
    generate_resources()