#ifndef MQL_AUTO_FORWARDS_INCLUDED_E6F83517906C7E62
#define MQL_AUTO_FORWARDS_INCLUDED_E6F83517906C7E62
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5

#line 314 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
bool UpdateGlobalVolatilityCache(void);
#line 466 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
CZone* GetZoneByName(string obj_name);
#line 545 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
bool RegisterUserZone(string obj_name);
#line 582 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void UpdateZoneCoordinates(string obj_name);
#line 632 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void RemoveZoneByName(string obj_name);
#line 677 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void NukeIrrelevantZones(void);
#line 714 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void MonitorZoneLifecycle(CLogger &log_instance, CArrayObj &zones, double atr, double multiplier);
#line 831 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void MergeZones(double atr);
#line 946 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void DetectDynamicZones(double atr, bool is_initial_scan);
#line 1035 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void TryCreateAutoZone(double p, ENUM_ZONE_TYPE t, datetime dt, double atr, int score, string tier, double vol_ratio, double velo_pips);
#line 1157 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void ResolvePendingInteractions(double atr);
#line 1372 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
void UpdateZoneVisuals(bool force_time_extension);
#line 1421 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Trading Supply and Demand Zones/Experts/4. 23547 DynamicSR4.mq5"
int AnalyzeZoneCandidate(int pivot_idx, ENUM_ZONE_TYPE type, double p, double atr, double &vol_ratio, double &velocity_pips, string &tier);

#endif
