#ifndef MQL_AUTO_FORWARDS_INCLUDED_3FC2D2EC681BC264
#define MQL_AUTO_FORWARDS_INCLUDED_3FC2D2EC681BC264
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5

#line 85 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
double GetPipSize();
#line 239 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
int AnalyzeMarketSwings(const datetime &time[], const double &high[], const double &low[]);
#line 333 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void EvaluateMarketStory();
#line 419 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void RenderChartVisuals();
#line 440 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void RenderMarketStoryPanel();
#line 480 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void RenderSwingInspectorPanel(const SwingPt &sw);
#line 514 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DrawPanelRow(string prefix, string label, string val, int x, int y, color val_clr);
#line 524 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void CreateOrUpdateRect(string name, int x, int y, int w, int h, color bg_clr, color border_clr);
#line 544 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void CreateOrUpdateLabel(string name, int x, int y, string text, color clr, int font_size, bool bold);
#line 563 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DrawSwingPoint(const datetime t, const double price, const int type, const string label);
#line 588 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DrawSegmentLine(const SwingPt &a, const SwingPt &b);
#line 605 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DrawEmptyMarketStoryPanel();
#line 615 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
bool IsSwingHigh(const int i, const double &high[]);
#line 630 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
bool IsSwingLow(const int i, const double &low[]);
#line 645 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
bool PassDistFilter(const double price, const double prev, const bool has_prev);
#line 655 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DeletePanelObjects(string panel_prefix);
#line 668 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/MarketBehaviorAnalyzer.mq5"
void DeleteAllObjects();

#endif
