#ifndef MQL_AUTO_FORWARDS_INCLUDED_D57411AFA3B14C48
#define MQL_AUTO_FORWARDS_INCLUDED_D57411AFA3B14C48
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Francis Nyoike Thumbi/Building a Stateful Trendline Management Framework/Indicators/SmartTrendlineManager/SmartTrendlineManager.mq5


#endif
