#ifndef MQL_AUTO_FORWARDS_INCLUDED_68AA8A5658FBFBDF
#define MQL_AUTO_FORWARDS_INCLUDED_68AA8A5658FBFBDF
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5

#line 411 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void OnInitDoEasy();
#line 635 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void OnDoEasyEvent(const int id, const long &lparam, const double &dparam, const string &sparam);
#line 1326 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void PressButtonsControl(void);
#line 1340 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
bool CreateButtons(const int shift_x, const int shift_y);
#line 1439 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
bool ButtonCreate(const string name, const int x, const int y, const int w, const int h, const string text, const color clr, const string font, const int font_size);
#line 1469 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
bool ButtonState(const string name);
#line 1476 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void ButtonState(const string name, const bool state);
#line 1499 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
string EnumToButtText(const ENUM_BUTTONS member);
#line 1520 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void PressButtonEvents(const string button_name);
#line 2564 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void SetPReqCriterion(const uchar id, const double price_activation, const ulong time_activation, ENUM_BUTTONS button, ENUM_COMPARER_TYPE comp_type, const double price_curr, const datetime time_curr);
#line 2599 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void SetStopLoss(void);
#line 2689 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void SetTakeProfit(void);
#line 2779 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void TrailingPositions(void);
#line 2849 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
void TrailingOrders(void);
#line 2957 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/1. 14339 Price patterns.mq5"
uint Rand(const uint min, const uint max);

#endif
