#ifndef MQL_AUTO_FORWARDS_INCLUDED_F556859B41263BAD
#define MQL_AUTO_FORWARDS_INCLUDED_F556859B41263BAD
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5

#line 429 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void OnInitDoEasy();
#line 652 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void OnDoEasyEvent(const int id, const long &lparam, const double &dparam, const string &sparam);
#line 1343 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void PressButtonsControl(void);
#line 1357 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
bool CreateButtons(const int shift_x, const int shift_y);
#line 1456 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
bool ButtonCreate(const string name, const int x, const int y, const int w, const int h, const string text, const color clr, const string font, const int font_size);
#line 1486 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
bool ButtonState(const string name);
#line 1493 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void ButtonState(const string name, const bool state);
#line 1516 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
string EnumToButtText(const ENUM_BUTTONS member);
#line 1537 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void PressButtonEvents(const string button_name);
#line 2581 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void SetPReqCriterion(const uchar id, const double price_activation, const ulong time_activation, ENUM_BUTTONS button, ENUM_COMPARER_TYPE comp_type, const double price_curr, const datetime time_curr);
#line 2611 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void SetStopLoss(void);
#line 2701 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void SetTakeProfit(void);
#line 2791 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void TrailingPositions(void);
#line 2861 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
void TrailingOrders(void);
#line 2969 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Artyom Trishkin/2. DoEasy. Service functions EA/2. 14479 Inside Bar pattern.mq5"
uint Rand(const uint min, const uint max);

#endif
