#ifndef MQL_AUTO_FORWARDS_INCLUDED_123D294F706BFD07
#define MQL_AUTO_FORWARDS_INCLUDED_123D294F706BFD07
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V11/EA Using Combination Lib V11.mq5

#line 244 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V11/EA Using Combination Lib V11.mq5"
void PushMarkerStyleToGraphicEngine(void);
#line 273 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V11/EA Using Combination Lib V11.mq5"
void AttachMarkerIndicatorToChart(void);

#endif
