#ifndef MQL_AUTO_FORWARDS_INCLUDED_E04E88F07C9B7607
#define MQL_AUTO_FORWARDS_INCLUDED_E04E88F07C9B7607
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V9/EA Using Combination Lib V9.mq5


#endif
