#ifndef MQL_AUTO_FORWARDS_INCLUDED_A3BAE6653716FC4A
#define MQL_AUTO_FORWARDS_INCLUDED_A3BAE6653716FC4A
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V1/EA Ussing Combination Lib.mq5

#line 392 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V1/EA Ussing Combination Lib.mq5"
bool IsCtrlKeyPressed(void);

#endif
