#ifndef MQL_AUTO_FORWARDS_INCLUDED_A84A8E0EA97F1C50
#define MQL_AUTO_FORWARDS_INCLUDED_A84A8E0EA97F1C50
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V10/EA Using Combination Lib V10.mq5

#line 453 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V10/EA Using Combination Lib V10.mq5"
void SetActiveChartSymbolTF(const string sym, const ENUM_TIMEFRAMES tf);
#line 481 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V10/EA Using Combination Lib V10.mq5"
void EnsureMarkerIndicatorAttached(void);
#line 522 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V10/EA Using Combination Lib V10.mq5"
void RemoveMarkerIndicator(void);
#line 530 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V10/EA Using Combination Lib V10.mq5"
void ReattachSignalMarkersIndicator(void);

#endif
