#ifndef MQL_AUTO_FORWARDS_INCLUDED_E0A49D23CA393F30
#define MQL_AUTO_FORWARDS_INCLUDED_E0A49D23CA393F30
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V3/EA Ussing Combination Lib V3.mq5

#line 159 "c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V3/EA Ussing Combination Lib V3.mq5"
bool IsCtrlKeyPressed(void);

#endif
