#ifndef MQL_AUTO_FORWARDS_INCLUDED_012DACA8189681EE
#define MQL_AUTO_FORWARDS_INCLUDED_012DACA8189681EE
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V6/Test Library Update/Test LIbrary Update V6.mq5


#endif
