#ifndef MQL_AUTO_FORWARDS_INCLUDED_0BE589B0C2F2F1A5
#define MQL_AUTO_FORWARDS_INCLUDED_0BE589B0C2F2F1A5
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/nguye/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/Experts/Anhnt/Example/4. Combination EA/V6/Test Library Update/TestComboBox/TestComboBox.mq5


#endif
